ALTER TABLE analyses DROP CONSTRAINT ck_analyses_category;
ALTER TABLE analyses ADD CONSTRAINT ck_analyses_category CHECK (error_category IS NULL OR error_category IN (
    'MAVEN_DEPENDENCY', 'GRADLE_DEPENDENCY', 'JAVA_COMPILATION', 'PYTHON_MODULE', 'DOCKER_BUILD',
    'JENKINS_PIPELINE', 'TEST_FAILURE', 'CONFIGURATION', 'CODE_SYNTAX', 'PYTHON_STATIC_ERROR', 'CODE_REVIEW', 'UNKNOWN'
));
