package com.devopscopilot.entity;

public enum ErrorCategory {
    MAVEN_DEPENDENCY, GRADLE_DEPENDENCY, JAVA_COMPILATION, PYTHON_MODULE,
    DOCKER_BUILD, JENKINS_PIPELINE, TEST_FAILURE, CONFIGURATION, CODE_SYNTAX, PYTHON_STATIC_ERROR, CODE_REVIEW, UNKNOWN
}
