import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import axios from "axios";
import { getDashboard } from "../api/dashboard";
import type { DashboardData } from "../api/dashboard";

export function DashboardPage() { const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(""); useEffect(() => { getDashboard().then(setData).catch(exception => setError(axios.isAxiosError(exception) ? exception.response?.data?.message ?? "Could not load dashboard" : "Could not load dashboard")); }, []); const topCategory = data?.commonCategories[0]; const stats = [["Total uploads", data?.totalUploads ?? "—", "All build logs"], ["Successful analyses", data?.successfulAnalyses ?? "—", `${data?.failedAnalyses ?? 0} failed analyses`], ["Top category", topCategory?.category.replaceAll("_", " ") ?? "—", topCategory ? `${topCategory.count} occurrences` : "No analyses yet"]]; const maxCount = Math.max(...(data?.commonCategories.map(item => item.count) ?? [1])); return <><header className="mb-7"><p className="text-sm font-medium text-blue-600">OVERVIEW</p><h1 className="text-3xl font-bold tracking-tight">Build intelligence at a glance</h1><p className="mt-2 text-slate-600">Upload a failed build log and get an explanation you can act on.</p></header>{error && <p className="mb-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
  <section className="mb-7 grid gap-4 sm:grid-cols-3">{stats.map(([label, value, hint]) => <div className="card p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></div>)}</section>
  <section className="card p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold">Analyze a new build failure</h2><p className="mt-1 text-sm text-slate-600">Supports Maven, Gradle, Java, Python, Docker, Jenkins, and text logs.</p></div><Link className="btn-primary" to="/upload">Upload a log</Link></div></section>
  <section className="mt-7 card p-6"><h2 className="font-bold">Most common error categories</h2><div className="mt-5 space-y-4">{data?.commonCategories.length ? data.commonCategories.slice(0, 3).map(item => <div key={item.category}><div className="mb-1 flex justify-between text-sm"><span>{item.category.replaceAll("_", " ")}</span><span className="font-medium">{item.count}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{ width: `${(item.count / maxCount) * 100}%` }} /></div></div>) : <p className="text-sm text-slate-500">Analyze a log to see category trends.</p>}</div></section></>; }
