import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { StatusBadge } from "../components/StatusBadge";
import axios from "axios";
import { getLogs } from "../api/logs";
import type { UploadedLog } from "../api/logs";

export function HistoryPage() { const [logs, setLogs] = useState<UploadedLog[]>([]); const [error, setError] = useState(""); useEffect(() => { getLogs().then(page => setLogs(page.content)).catch(exception => setError(axios.isAxiosError(exception) ? exception.response?.data?.message ?? "Could not load history" : "Could not load history")); }, []); return <><header className="mb-7"><p className="text-sm font-medium text-blue-600">HISTORY</p><h1 className="text-3xl font-bold">Uploaded build logs</h1><p className="mt-2 text-slate-600">Review previous build-failure analyses.</p></header>{error && <p className="mb-5 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
  <section className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Log file</th><th className="px-5 py-3">Detected source</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Uploaded</th><th className="px-5 py-3" /></tr></thead><tbody>{logs.map(item => <tr className="border-t border-slate-100" key={item.id}><td className="px-5 py-4 font-medium">{item.originalFilename}</td><td className="px-5 py-4">{item.sourceType.replaceAll("_", " ")}</td><td className="px-5 py-4"><StatusBadge value={item.uploadStatus} /></td><td className="px-5 py-4 text-slate-500">{new Date(item.uploadedAt).toLocaleString()}</td><td className="px-5 py-4"><Link className="font-semibold text-blue-600" to={`/analysis/${item.id}`}>View</Link></td></tr>)}{!logs.length && !error && <tr><td className="px-5 py-8 text-center text-slate-500" colSpan={5}>No logs uploaded yet.</td></tr>}</tbody></table></div></section></>; }
